# Generated by Django 3.1 on 2021-12-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], default=1)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], default=1)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=200)),
            ],
        ),
    ]
