# Generated by Django 3.1 on 2021-12-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
        ("movie", "0002_movie_synopsis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="main_actor",
        ),
        migrations.AddField(
            model_name="movie",
            name="main_actor",
            field=models.ManyToManyField(to="person.Actor"),
        ),
        migrations.RemoveField(
            model_name="movie",
            name="main_author",
        ),
        migrations.AddField(
            model_name="movie",
            name="main_author",
            field=models.ManyToManyField(to="person.Author"),
        ),
    ]
