# Generated by Django 3.1 on 2022-05-04 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_movie_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="score",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ]
            ),
        ),
    ]
